BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ai-assistant"
BBFILE_PATTERN_meta-ai-assistant = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ai-assistant = "7"

LAYERSERIES_COMPAT_meta-ai-assistant = "scarthgap"
